# Generated by Django 3.0.1 on 2020-02-03 11:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdvancedUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('profile_image', models.ImageField(default='img/default_image.jpg', upload_to='user/profile_image')),
                ('is_activated', models.BooleanField(db_index=True, default=True, verbose_name='Прошел активацию')),
                ('send_messages', models.BooleanField(default=True, verbose_name='Слать оповещения о новых комментариях?')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MainTaskBoard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board_name', models.CharField(default='Task board', max_length=50, verbose_name='Назови доску задач')),
                ('created_at', models.DateField(editable=False, verbose_name='Создано')),
                ('creator', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Доска задач',
                'verbose_name_plural': 'Доски задач',
            },
        ),
        migrations.CreateModel(
            name='TaskInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('description', models.TextField(blank=True, max_length=2000, verbose_name='Дополнительное описание задачи')),
                ('t_duration', models.CharField(choices=[('9000', 'Бессрочные'), ('1', 'Ежедневные'), ('80', 'Долгосрочные'), ('7', 'Еженедельные')], max_length=10, verbose_name='Длительность')),
                ('created_at', models.DateField(editable=False, verbose_name='Создано')),
                ('visible', models.BooleanField(default=True, verbose_name='Кто видит задачу? Только я/Все')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('main_board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.MainTaskBoard')),
            ],
            options={
                'verbose_name': 'Задача',
                'verbose_name_plural': 'Задачи',
                'ordering': ['author', 't_duration'],
            },
        ),
        migrations.CreateModel(
            name='Mark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t_status', models.CharField(choices=[('done', 'done'), ('undone', 'undone'), ('in_progress', 'in_progress')], default=('undone', 'undone'), max_length=50)),
                ('created_at', models.DateField(editable=False)),
                ('task_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.TaskInfo')),
            ],
            options={
                'verbose_name': 'Отметка',
                'verbose_name_plural': 'Отметки',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=500, verbose_name='Имя')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.TaskInfo')),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
            },
        ),
        migrations.AddField(
            model_name='advanceduser',
            name='board',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.MainTaskBoard'),
        ),
    ]
