# Generated by Django 3.0.1 on 2020-02-03 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskinfo',
            name='t_duration',
            field=models.CharField(choices=[('7', 'Еженедельные'), ('80', 'Долгосрочные'), ('1', 'Ежедневные'), ('9000', 'Бессрочные')], max_length=10, verbose_name='Длительность'),
        ),
    ]
