# Generated by Django 3.0.1 on 2020-01-10 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DailyTask',
            new_name='Mark',
        ),
    ]
