# Generated by Django 3.0.1 on 2020-01-27 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskinfo',
            name='t_duration',
            field=models.CharField(choices=[('9000', 'Бессрочные'), ('80', 'Долгосрочные'), ('7', 'Еженедельные'), ('1', 'Ежедневные')], max_length=10, verbose_name='Длительность'),
        ),
    ]
