# Generated by Django 3.0.1 on 2020-01-23 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advanceduser',
            name='board',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.MainTaskBoard'),
        ),
        migrations.AlterField(
            model_name='taskinfo',
            name='t_duration',
            field=models.CharField(choices=[('1000', 'Бессрочные'), ('7', 'Еженедельные'), ('30', 'Долгосрочные'), ('1', 'Ежедневные')], max_length=10, verbose_name='Длительность'),
        ),
    ]
