# Generated by Django 3.0.1 on 2020-01-09 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintaskboard',
            name='board_name',
            field=models.CharField(default='Task board', max_length=50, verbose_name='Назови доску задач'),
        ),
    ]
