# Generated by Django 3.0.1 on 2020-01-10 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200110_1335'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mark',
            old_name='life_period',
            new_name='end_date',
        ),
    ]
