# Generated by Django 3.0.1 on 2020-01-09 02:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0002_maintaskboard_board_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maintaskboard',
            name='friend',
        ),
        migrations.AddField(
            model_name='maintaskboard',
            name='friends',
            field=models.ManyToManyField(related_name='friends', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='taskinfo',
            name='author',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='taskinfo',
            name='main_board',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.MainTaskBoard'),
        ),
    ]
