# Generated by Django 3.0.1 on 2020-02-06 12:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200203_1140'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advanceduser',
            name='is_activated',
        ),
        migrations.RemoveField(
            model_name='advanceduser',
            name='send_messages',
        ),
        migrations.AddField(
            model_name='advanceduser',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='advanceduser',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='taskinfo',
            name='t_duration',
            field=models.CharField(choices=[('80', 'Долгосрочные'), ('9000', 'Бессрочные'), ('7', 'Еженедельные'), ('1', 'Ежедневные')], max_length=10, verbose_name='Длительность'),
        ),
    ]
