# Generated by Django 3.0.1 on 2020-01-09 02:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0003_auto_20200109_0232'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dailytask',
            options={'verbose_name': 'Отметка', 'verbose_name_plural': 'Отметка'},
        ),
        migrations.AlterModelOptions(
            name='taskinfo',
            options={'verbose_name': 'Задача', 'verbose_name_plural': 'Задачи'},
        ),
        migrations.AlterField(
            model_name='taskinfo',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='taskinfo',
            name='main_board',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.MainTaskBoard'),
        ),
    ]
