# Generated by Django 3.0.1 on 2020-01-16 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200110_1346'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taskinfo',
            options={'ordering': ['author', 't_duration'], 'verbose_name': 'Задача', 'verbose_name_plural': 'Задачи'},
        ),
        migrations.AddField(
            model_name='advanceduser',
            name='board',
            field=models.ManyToManyField(to='main.MainTaskBoard'),
        ),
        migrations.AlterField(
            model_name='taskinfo',
            name='t_duration',
            field=models.CharField(choices=[('week', 'week'), ('day', 'day'), ('long', 'long'), ('single', 'single')], max_length=10),
        ),
    ]
