# Generated by Django 3.0.1 on 2020-02-06 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200206_1252'),
    ]

    operations = [
        migrations.AddField(
            model_name='advanceduser',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='taskinfo',
            name='t_duration',
            field=models.CharField(choices=[('1', 'Ежедневные'), ('7', 'Еженедельные'), ('80', 'Долгосрочные'), ('9000', 'Бессрочные')], max_length=10, verbose_name='Длительность'),
        ),
    ]
