# Generated by Django 3.0.1 on 2020-01-09 03:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0004_auto_20200109_0237'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maintaskboard',
            name='friends',
        ),
        migrations.AddField(
            model_name='maintaskboard',
            name='members',
            field=models.ManyToManyField(default=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор'), related_name='friends', to=settings.AUTH_USER_MODEL),
        ),
    ]
