# Generated by Django 3.0.1 on 2020-01-16 20:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20200116_2016'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advanceduser',
            name='board',
        ),
        migrations.AddField(
            model_name='advanceduser',
            name='board',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='main.MainTaskBoard'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='taskinfo',
            name='t_duration',
            field=models.CharField(choices=[('long', 'long'), ('day', 'day'), ('single', 'single'), ('week', 'week')], max_length=10),
        ),
    ]
