# Generated by Django 3.0.1 on 2020-02-06 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('main', '0004_auto_20200206_1311'),
    ]

    operations = [
        migrations.AddField(
            model_name='advanceduser',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='advanceduser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
        migrations.AlterField(
            model_name='taskinfo',
            name='t_duration',
            field=models.CharField(choices=[('80', 'Долгосрочные'), ('1', 'Ежедневные'), ('9000', 'Бессрочные'), ('7', 'Еженедельные')], max_length=10, verbose_name='Длительность'),
        ),
    ]
