# Generated by Django 3.0.1 on 2020-02-10 10:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20200206_1922'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advanceduser',
            name='board',
        ),
        migrations.RemoveField(
            model_name='maintaskboard',
            name='creator',
        ),
        migrations.AddField(
            model_name='maintaskboard',
            name='members',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='taskinfo',
            name='t_duration',
            field=models.CharField(choices=[('1', 'Ежедневные'), ('80', 'Долгосрочные'), ('9000', 'Бессрочные'), ('7', 'Еженедельные')], max_length=10, verbose_name='Длительность'),
        ),
    ]
