# Generated by Django 3.0.1 on 2020-01-21 08:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20200116_2057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskinfo',
            name='description',
            field=models.TextField(blank=True, max_length=2000, verbose_name='Дополнительное описание задачи'),
        ),
        migrations.AlterField(
            model_name='taskinfo',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='taskinfo',
            name='t_duration',
            field=models.CharField(choices=[('30', 'Долгосрочные'), ('1', 'Ежедневные'), ('7', 'Еженедельные'), ('1000', 'Бессрочные')], max_length=10, verbose_name='Длительность'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=500, verbose_name='Имя')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.TaskInfo')),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
            },
        ),
    ]
