# Generated by Django 3.0.1 on 2020-01-09 03:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0005_auto_20200109_0306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintaskboard',
            name='members',
            field=models.ManyToManyField(related_name='friends', to=settings.AUTH_USER_MODEL),
        ),
    ]
