# Generated by Django 3.0.1 on 2020-01-21 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20200121_0808'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskinfo',
            name='visible',
            field=models.BooleanField(default=True, verbose_name='Кто видит задачу? Только я/Все'),
        ),
        migrations.AlterField(
            model_name='taskinfo',
            name='t_duration',
            field=models.CharField(choices=[('1000', 'Бессрочные'), ('1', 'Ежедневные'), ('30', 'Долгосрочные'), ('7', 'Еженедельные')], max_length=10, verbose_name='Длительность'),
        ),
    ]
