# Generated by Django 3.0.1 on 2020-02-10 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20200210_1040'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advanceduser',
            name='myboard',
        ),
        migrations.AddField(
            model_name='advanceduser',
            name='board',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='member', to='main.MainTaskBoard'),
        ),
        migrations.AlterField(
            model_name='taskinfo',
            name='t_duration',
            field=models.CharField(choices=[('1', 'Ежедневные'), ('9000', 'Бессрочные'), ('80', 'Долгосрочные'), ('7', 'Еженедельные')], max_length=10, verbose_name='Длительность'),
        ),
    ]
