# Generated by Django 3.0.1 on 2020-02-10 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20200210_1041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskinfo',
            name='t_duration',
            field=models.CharField(choices=[('9000', 'Бессрочные'), ('1', 'Ежедневные'), ('7', 'Еженедельные'), ('80', 'Долгосрочные')], max_length=10, verbose_name='Длительность'),
        ),
    ]
