# Generated by Django 3.0.1 on 2020-02-10 12:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20200210_1043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advanceduser',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='maintaskboard',
            name='board_name',
            field=models.CharField(max_length=50, verbose_name='Board Name'),
        ),
        migrations.AlterField(
            model_name='maintaskboard',
            name='created_at',
            field=models.DateField(editable=False, verbose_name='Creates'),
        ),
        migrations.AlterField(
            model_name='maintaskboard',
            name='creator',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='taskinfo',
            name='t_duration',
            field=models.CharField(choices=[('1', 'Ежедневные'), ('7', 'Еженедельные'), ('80', 'Долгосрочные'), ('9000', 'Бессрочные')], max_length=10, verbose_name='Длительность'),
        ),
    ]
